### ISSUE TITLE
Returns invalid error object on invalid JSX

### ISSUE THREAD

**Issue by sindresorhus** [shmatov/jshint-jsx#5]
https://github.com/sindresorhus/atom-jshint/issues/57

When supplied invalid JSX it will return an invalid error object in the `linter.errors` array:

```
character: undefined
line: NaN
reason: undefined
```

It should return a valid error or an empty array.

**Comment by shmatov** [comment]
Sorry for such a long delay. I missed the notification :confused: 
This issue is fixed!
